name: Release
on:
  push:
    tags:
    - 'v*.*.*'
env:
  ONLINE_REGISTER: ghcr.io/jiuker-middware
  BUILD_PLATFORM: linux/amd64,linux/arm64
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone mysql-operator repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: mysql-operator
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./
          file: ./arm64/images/mysql-operator/Release-Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
             ${{ env.ONLINE_REGISTER }}/mysql-operator:${{ github.ref_name }}
             ${{ env.ONLINE_REGISTER }}/mysql-operator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: mysql-operator-orchestrator
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./
          file: ./arm64/images/mysql-operator-orchestrator/Release-Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
             ${{ env.ONLINE_REGISTER }}/mysql-operator-orchestrator:${{ github.ref_name }}
             ${{ env.ONLINE_REGISTER }}/mysql-operator-orchestrator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: mysql-operator-sidecar-5.7
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./
          file: ./arm64/images/mysql-operator-sidecar-5.7/Release-Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
             ${{ env.ONLINE_REGISTER }}/mysql-operator-sidecar-5.7:${{ github.ref_name }}
             ${{ env.ONLINE_REGISTER }}/mysql-operator-sidecar-5.7:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: mysql-operator-sidecar-8.0
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./
          file: ./arm64/images/mysql-operator-sidecar-8.0/Release-Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
             ${{ env.ONLINE_REGISTER }}/mysql-operator-sidecar-8.0:${{ github.ref_name }}
             ${{ env.ONLINE_REGISTER }}/mysql-operator-sidecar-8.0:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  helm_release:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone mysql-operator repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Generate Helm charts
        run: |
          helm package ./deploy/charts/mysql-operator -d ./dist --version ${{ github.ref_name }}
      - name: Release and upload packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dist/mysql-operator-${{ github.ref_name }}.tgz
