name: Release
on:
  push:
    tags:
    - 'v*.*.*'
env:
  ONLINE_REGISTER: ghcr.io/ksmartdata
  BUILD_PLATFORM: linux/amd64,linux/arm64
jobs:
  ot-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone mysql-operator repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: mysql-operator
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./arm64/images/ot-redis
          file: ./arm64/images/ot-redis/Dockerfile-release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
            ${{ env.ONLINE_REGISTER }}/ot-redis:v6.2.56
            ${{ env.ONLINE_REGISTER }}/ot-redis:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
#  ot-redis-operator:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Git clone mysql-operator repo
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2.0.0
#      - name: mysql-operator
#        uses: docker/build-push-action@v3.1.1
#        with:
#          context: ./
#          file: ./arm64/images/ot-redis-operator/Dockerfile
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          push: true
#          platforms: ${{ env.BUILD_PLATFORM }}
#          tags: |
#             ${{ env.ONLINE_REGISTER }}/ot-redis-operator:v0.13.0
#             ${{ env.ONLINE_REGISTER }}/ot-redis-operator:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max